// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"qcgo/models"
)

// DeleteResourcesByIDOKCode is the HTTP code returned for type DeleteResourcesByIDOK
const DeleteResourcesByIDOKCode int = 200

/*DeleteResourcesByIDOK OK

swagger:response deleteResourcesByIdOK
*/
type DeleteResourcesByIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Resource `json:"body,omitempty"`
}

// NewDeleteResourcesByIDOK creates DeleteResourcesByIDOK with default headers values
func NewDeleteResourcesByIDOK() *DeleteResourcesByIDOK {

	return &DeleteResourcesByIDOK{}
}

// WithPayload adds the payload to the delete resources by Id o k response
func (o *DeleteResourcesByIDOK) WithPayload(payload []*models.Resource) *DeleteResourcesByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id o k response
func (o *DeleteResourcesByIDOK) SetPayload(payload []*models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Resource, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteResourcesByIDBadRequestCode is the HTTP code returned for type DeleteResourcesByIDBadRequest
const DeleteResourcesByIDBadRequestCode int = 400

/*DeleteResourcesByIDBadRequest Bad Request

swagger:response deleteResourcesByIdBadRequest
*/
type DeleteResourcesByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewDeleteResourcesByIDBadRequest creates DeleteResourcesByIDBadRequest with default headers values
func NewDeleteResourcesByIDBadRequest() *DeleteResourcesByIDBadRequest {

	return &DeleteResourcesByIDBadRequest{}
}

// WithPayload adds the payload to the delete resources by Id bad request response
func (o *DeleteResourcesByIDBadRequest) WithPayload(payload *models.SimpleResponse) *DeleteResourcesByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id bad request response
func (o *DeleteResourcesByIDBadRequest) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourcesByIDUnauthorizedCode is the HTTP code returned for type DeleteResourcesByIDUnauthorized
const DeleteResourcesByIDUnauthorizedCode int = 401

/*DeleteResourcesByIDUnauthorized Unauthorized

swagger:response deleteResourcesByIdUnauthorized
*/
type DeleteResourcesByIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewDeleteResourcesByIDUnauthorized creates DeleteResourcesByIDUnauthorized with default headers values
func NewDeleteResourcesByIDUnauthorized() *DeleteResourcesByIDUnauthorized {

	return &DeleteResourcesByIDUnauthorized{}
}

// WithPayload adds the payload to the delete resources by Id unauthorized response
func (o *DeleteResourcesByIDUnauthorized) WithPayload(payload *models.SimpleResponse) *DeleteResourcesByIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id unauthorized response
func (o *DeleteResourcesByIDUnauthorized) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourcesByIDNotFoundCode is the HTTP code returned for type DeleteResourcesByIDNotFound
const DeleteResourcesByIDNotFoundCode int = 404

/*DeleteResourcesByIDNotFound Not Found

swagger:response deleteResourcesByIdNotFound
*/
type DeleteResourcesByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewDeleteResourcesByIDNotFound creates DeleteResourcesByIDNotFound with default headers values
func NewDeleteResourcesByIDNotFound() *DeleteResourcesByIDNotFound {

	return &DeleteResourcesByIDNotFound{}
}

// WithPayload adds the payload to the delete resources by Id not found response
func (o *DeleteResourcesByIDNotFound) WithPayload(payload *models.SimpleResponse) *DeleteResourcesByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id not found response
func (o *DeleteResourcesByIDNotFound) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourcesByIDUnprocessableEntityCode is the HTTP code returned for type DeleteResourcesByIDUnprocessableEntity
const DeleteResourcesByIDUnprocessableEntityCode int = 422

/*DeleteResourcesByIDUnprocessableEntity Unprocessable

swagger:response deleteResourcesByIdUnprocessableEntity
*/
type DeleteResourcesByIDUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewDeleteResourcesByIDUnprocessableEntity creates DeleteResourcesByIDUnprocessableEntity with default headers values
func NewDeleteResourcesByIDUnprocessableEntity() *DeleteResourcesByIDUnprocessableEntity {

	return &DeleteResourcesByIDUnprocessableEntity{}
}

// WithPayload adds the payload to the delete resources by Id unprocessable entity response
func (o *DeleteResourcesByIDUnprocessableEntity) WithPayload(payload *models.SimpleResponse) *DeleteResourcesByIDUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id unprocessable entity response
func (o *DeleteResourcesByIDUnprocessableEntity) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourcesByIDInternalServerErrorCode is the HTTP code returned for type DeleteResourcesByIDInternalServerError
const DeleteResourcesByIDInternalServerErrorCode int = 500

/*DeleteResourcesByIDInternalServerError Internal Server Error

swagger:response deleteResourcesByIdInternalServerError
*/
type DeleteResourcesByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewDeleteResourcesByIDInternalServerError creates DeleteResourcesByIDInternalServerError with default headers values
func NewDeleteResourcesByIDInternalServerError() *DeleteResourcesByIDInternalServerError {

	return &DeleteResourcesByIDInternalServerError{}
}

// WithPayload adds the payload to the delete resources by Id internal server error response
func (o *DeleteResourcesByIDInternalServerError) WithPayload(payload *models.SimpleResponse) *DeleteResourcesByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id internal server error response
func (o *DeleteResourcesByIDInternalServerError) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteResourcesByIDServiceUnavailableCode is the HTTP code returned for type DeleteResourcesByIDServiceUnavailable
const DeleteResourcesByIDServiceUnavailableCode int = 503

/*DeleteResourcesByIDServiceUnavailable Service Unavailable

swagger:response deleteResourcesByIdServiceUnavailable
*/
type DeleteResourcesByIDServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewDeleteResourcesByIDServiceUnavailable creates DeleteResourcesByIDServiceUnavailable with default headers values
func NewDeleteResourcesByIDServiceUnavailable() *DeleteResourcesByIDServiceUnavailable {

	return &DeleteResourcesByIDServiceUnavailable{}
}

// WithPayload adds the payload to the delete resources by Id service unavailable response
func (o *DeleteResourcesByIDServiceUnavailable) WithPayload(payload *models.SimpleResponse) *DeleteResourcesByIDServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete resources by Id service unavailable response
func (o *DeleteResourcesByIDServiceUnavailable) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteResourcesByIDServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
