// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"qcgo/models"
)

// GetResourcesByIDOKCode is the HTTP code returned for type GetResourcesByIDOK
const GetResourcesByIDOKCode int = 200

/*GetResourcesByIDOK OK

swagger:response getResourcesByIdOK
*/
type GetResourcesByIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Resource `json:"body,omitempty"`
}

// NewGetResourcesByIDOK creates GetResourcesByIDOK with default headers values
func NewGetResourcesByIDOK() *GetResourcesByIDOK {

	return &GetResourcesByIDOK{}
}

// WithPayload adds the payload to the get resources by Id o k response
func (o *GetResourcesByIDOK) WithPayload(payload []*models.Resource) *GetResourcesByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id o k response
func (o *GetResourcesByIDOK) SetPayload(payload []*models.Resource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Resource, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetResourcesByIDBadRequestCode is the HTTP code returned for type GetResourcesByIDBadRequest
const GetResourcesByIDBadRequestCode int = 400

/*GetResourcesByIDBadRequest Bad Request

swagger:response getResourcesByIdBadRequest
*/
type GetResourcesByIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetResourcesByIDBadRequest creates GetResourcesByIDBadRequest with default headers values
func NewGetResourcesByIDBadRequest() *GetResourcesByIDBadRequest {

	return &GetResourcesByIDBadRequest{}
}

// WithPayload adds the payload to the get resources by Id bad request response
func (o *GetResourcesByIDBadRequest) WithPayload(payload *models.SimpleResponse) *GetResourcesByIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id bad request response
func (o *GetResourcesByIDBadRequest) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourcesByIDUnauthorizedCode is the HTTP code returned for type GetResourcesByIDUnauthorized
const GetResourcesByIDUnauthorizedCode int = 401

/*GetResourcesByIDUnauthorized Unauthorized

swagger:response getResourcesByIdUnauthorized
*/
type GetResourcesByIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetResourcesByIDUnauthorized creates GetResourcesByIDUnauthorized with default headers values
func NewGetResourcesByIDUnauthorized() *GetResourcesByIDUnauthorized {

	return &GetResourcesByIDUnauthorized{}
}

// WithPayload adds the payload to the get resources by Id unauthorized response
func (o *GetResourcesByIDUnauthorized) WithPayload(payload *models.SimpleResponse) *GetResourcesByIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id unauthorized response
func (o *GetResourcesByIDUnauthorized) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourcesByIDNotFoundCode is the HTTP code returned for type GetResourcesByIDNotFound
const GetResourcesByIDNotFoundCode int = 404

/*GetResourcesByIDNotFound Not Found

swagger:response getResourcesByIdNotFound
*/
type GetResourcesByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetResourcesByIDNotFound creates GetResourcesByIDNotFound with default headers values
func NewGetResourcesByIDNotFound() *GetResourcesByIDNotFound {

	return &GetResourcesByIDNotFound{}
}

// WithPayload adds the payload to the get resources by Id not found response
func (o *GetResourcesByIDNotFound) WithPayload(payload *models.SimpleResponse) *GetResourcesByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id not found response
func (o *GetResourcesByIDNotFound) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourcesByIDUnprocessableEntityCode is the HTTP code returned for type GetResourcesByIDUnprocessableEntity
const GetResourcesByIDUnprocessableEntityCode int = 422

/*GetResourcesByIDUnprocessableEntity Unprocessable

swagger:response getResourcesByIdUnprocessableEntity
*/
type GetResourcesByIDUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetResourcesByIDUnprocessableEntity creates GetResourcesByIDUnprocessableEntity with default headers values
func NewGetResourcesByIDUnprocessableEntity() *GetResourcesByIDUnprocessableEntity {

	return &GetResourcesByIDUnprocessableEntity{}
}

// WithPayload adds the payload to the get resources by Id unprocessable entity response
func (o *GetResourcesByIDUnprocessableEntity) WithPayload(payload *models.SimpleResponse) *GetResourcesByIDUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id unprocessable entity response
func (o *GetResourcesByIDUnprocessableEntity) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourcesByIDInternalServerErrorCode is the HTTP code returned for type GetResourcesByIDInternalServerError
const GetResourcesByIDInternalServerErrorCode int = 500

/*GetResourcesByIDInternalServerError Internal Server Error

swagger:response getResourcesByIdInternalServerError
*/
type GetResourcesByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetResourcesByIDInternalServerError creates GetResourcesByIDInternalServerError with default headers values
func NewGetResourcesByIDInternalServerError() *GetResourcesByIDInternalServerError {

	return &GetResourcesByIDInternalServerError{}
}

// WithPayload adds the payload to the get resources by Id internal server error response
func (o *GetResourcesByIDInternalServerError) WithPayload(payload *models.SimpleResponse) *GetResourcesByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id internal server error response
func (o *GetResourcesByIDInternalServerError) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetResourcesByIDServiceUnavailableCode is the HTTP code returned for type GetResourcesByIDServiceUnavailable
const GetResourcesByIDServiceUnavailableCode int = 503

/*GetResourcesByIDServiceUnavailable Service Unavailable

swagger:response getResourcesByIdServiceUnavailable
*/
type GetResourcesByIDServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetResourcesByIDServiceUnavailable creates GetResourcesByIDServiceUnavailable with default headers values
func NewGetResourcesByIDServiceUnavailable() *GetResourcesByIDServiceUnavailable {

	return &GetResourcesByIDServiceUnavailable{}
}

// WithPayload adds the payload to the get resources by Id service unavailable response
func (o *GetResourcesByIDServiceUnavailable) WithPayload(payload *models.SimpleResponse) *GetResourcesByIDServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get resources by Id service unavailable response
func (o *GetResourcesByIDServiceUnavailable) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetResourcesByIDServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
