// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetResourcesByIDParams creates a new GetResourcesByIDParams object
//
// There are no default values defined in the spec.
func NewGetResourcesByIDParams() GetResourcesByIDParams {

	return GetResourcesByIDParams{}
}

// GetResourcesByIDParams contains all the bound params for the get resources by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getResourcesById
type GetResourcesByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*resourceId
	  Required: true
	  In: path
	*/
	ResourceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetResourcesByIDParams() beforehand.
func (o *GetResourcesByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rResourceID, rhkResourceID, _ := route.Params.GetOK("resourceId")
	if err := o.bindResourceID(rResourceID, rhkResourceID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindResourceID binds and validates parameter ResourceID from path.
func (o *GetResourcesByIDParams) bindResourceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ResourceID = raw

	return nil
}
