// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"qcgo/models"
)

// PostResourceByAppCodeCreatedCode is the HTTP code returned for type PostResourceByAppCodeCreated
const PostResourceByAppCodeCreatedCode int = 201

/*PostResourceByAppCodeCreated Created

swagger:response postResourceByAppCodeCreated
*/
type PostResourceByAppCodeCreated struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewPostResourceByAppCodeCreated creates PostResourceByAppCodeCreated with default headers values
func NewPostResourceByAppCodeCreated() *PostResourceByAppCodeCreated {

	return &PostResourceByAppCodeCreated{}
}

// WithPayload adds the payload to the post resource by app code created response
func (o *PostResourceByAppCodeCreated) WithPayload(payload *models.SimpleResponse) *PostResourceByAppCodeCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource by app code created response
func (o *PostResourceByAppCodeCreated) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceByAppCodeCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResourceByAppCodeBadRequestCode is the HTTP code returned for type PostResourceByAppCodeBadRequest
const PostResourceByAppCodeBadRequestCode int = 400

/*PostResourceByAppCodeBadRequest Bad Request

swagger:response postResourceByAppCodeBadRequest
*/
type PostResourceByAppCodeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewPostResourceByAppCodeBadRequest creates PostResourceByAppCodeBadRequest with default headers values
func NewPostResourceByAppCodeBadRequest() *PostResourceByAppCodeBadRequest {

	return &PostResourceByAppCodeBadRequest{}
}

// WithPayload adds the payload to the post resource by app code bad request response
func (o *PostResourceByAppCodeBadRequest) WithPayload(payload *models.SimpleResponse) *PostResourceByAppCodeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource by app code bad request response
func (o *PostResourceByAppCodeBadRequest) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceByAppCodeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResourceByAppCodeUnauthorizedCode is the HTTP code returned for type PostResourceByAppCodeUnauthorized
const PostResourceByAppCodeUnauthorizedCode int = 401

/*PostResourceByAppCodeUnauthorized Unauthorized

swagger:response postResourceByAppCodeUnauthorized
*/
type PostResourceByAppCodeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewPostResourceByAppCodeUnauthorized creates PostResourceByAppCodeUnauthorized with default headers values
func NewPostResourceByAppCodeUnauthorized() *PostResourceByAppCodeUnauthorized {

	return &PostResourceByAppCodeUnauthorized{}
}

// WithPayload adds the payload to the post resource by app code unauthorized response
func (o *PostResourceByAppCodeUnauthorized) WithPayload(payload *models.SimpleResponse) *PostResourceByAppCodeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource by app code unauthorized response
func (o *PostResourceByAppCodeUnauthorized) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceByAppCodeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResourceByAppCodeUnprocessableEntityCode is the HTTP code returned for type PostResourceByAppCodeUnprocessableEntity
const PostResourceByAppCodeUnprocessableEntityCode int = 422

/*PostResourceByAppCodeUnprocessableEntity Unprocessable

swagger:response postResourceByAppCodeUnprocessableEntity
*/
type PostResourceByAppCodeUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewPostResourceByAppCodeUnprocessableEntity creates PostResourceByAppCodeUnprocessableEntity with default headers values
func NewPostResourceByAppCodeUnprocessableEntity() *PostResourceByAppCodeUnprocessableEntity {

	return &PostResourceByAppCodeUnprocessableEntity{}
}

// WithPayload adds the payload to the post resource by app code unprocessable entity response
func (o *PostResourceByAppCodeUnprocessableEntity) WithPayload(payload *models.SimpleResponse) *PostResourceByAppCodeUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource by app code unprocessable entity response
func (o *PostResourceByAppCodeUnprocessableEntity) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceByAppCodeUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostResourceByAppCodeInternalServerErrorCode is the HTTP code returned for type PostResourceByAppCodeInternalServerError
const PostResourceByAppCodeInternalServerErrorCode int = 500

/*PostResourceByAppCodeInternalServerError Internal Server Error

swagger:response postResourceByAppCodeInternalServerError
*/
type PostResourceByAppCodeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewPostResourceByAppCodeInternalServerError creates PostResourceByAppCodeInternalServerError with default headers values
func NewPostResourceByAppCodeInternalServerError() *PostResourceByAppCodeInternalServerError {

	return &PostResourceByAppCodeInternalServerError{}
}

// WithPayload adds the payload to the post resource by app code internal server error response
func (o *PostResourceByAppCodeInternalServerError) WithPayload(payload *models.SimpleResponse) *PostResourceByAppCodeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resource by app code internal server error response
func (o *PostResourceByAppCodeInternalServerError) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResourceByAppCodeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
