// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateResourcesByIDHandlerFunc turns a function with the right signature into a update resources by Id handler
type UpdateResourcesByIDHandlerFunc func(UpdateResourcesByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateResourcesByIDHandlerFunc) Handle(params UpdateResourcesByIDParams) middleware.Responder {
	return fn(params)
}

// UpdateResourcesByIDHandler interface for that can handle valid update resources by Id params
type UpdateResourcesByIDHandler interface {
	Handle(UpdateResourcesByIDParams) middleware.Responder
}

// NewUpdateResourcesByID creates a new http.Handler for the update resources by Id operation
func NewUpdateResourcesByID(ctx *middleware.Context, handler UpdateResourcesByIDHandler) *UpdateResourcesByID {
	return &UpdateResourcesByID{Context: ctx, Handler: handler}
}

/* UpdateResourcesByID swagger:route PUT /{resourceId}/ Service updateResourcesById

Update resource

*/
type UpdateResourcesByID struct {
	Context *middleware.Context
	Handler UpdateResourcesByIDHandler
}

func (o *UpdateResourcesByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateResourcesByIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
