// Code generated by go-swagger; DO NOT EDIT.

// Package restapi SERVICE
//
//  Service API
//  Schemes:
//    https
//  Host: localhost:8080
//  BasePath: /service
//  Version: 1.0.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
