swagger: '2.0'
info:
  description:  Service API
  version: 1.0.0.0
  title: SERVICE
schemes:
  - https
basePath: /service
consumes:
  - application/json
produces:
  - application/json
host: localhost:8080
x-google-endpoints:
  - name: service

paths:
  /Resource:
    post:
      tags:
        - Service
      summary: Create a new resource for a given application.
      operationId: postResourceByAppCode
      parameters:
        - in: body
          name: body
          description: Create a new resource
          required: true
          schema:
            $ref: '#/definitions/Resource'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/SimpleResponse'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/SimpleResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/SimpleResponse'
        '422':
          description: Unprocessable
          schema:
            $ref: '#/definitions/SimpleResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/SimpleResponse'
  /{resourceId}/:
    get:
      tags:
        - Service
      summary: Get  resources 
      operationId: getResourcesById
      parameters:
        - in: path
          description: resourceId
          name: resourceId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Resource'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/SimpleResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/SimpleResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/SimpleResponse'
        '422':
          description: Unprocessable
          schema:
            $ref: '#/definitions/SimpleResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/SimpleResponse'
        '503':
          description: Service Unavailable
          schema:
            $ref: '#/definitions/SimpleResponse'
    delete:
      tags:
        - Service
      summary: Delete resources 
      operationId: DeleteResourcesById
      parameters:
        - in: path
          description: resourceId
          name: resourceId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Resource'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/SimpleResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/SimpleResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/SimpleResponse'
        '422':
          description: Unprocessable
          schema:
            $ref: '#/definitions/SimpleResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/SimpleResponse'
        '503':
          description: Service Unavailable
          schema:
            $ref: '#/definitions/SimpleResponse'
    put:
      tags:
        - Service
      summary: Update resource
      operationId: UpdateResourcesById
      parameters:
        - in: path
          description: resourceId
          name: resourceId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Resource'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/SimpleResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/SimpleResponse'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/SimpleResponse'
        '422':
          description: Unprocessable
          schema:
            $ref: '#/definitions/SimpleResponse'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/SimpleResponse'
        '503':
          description: Service Unavailable
          schema:
            $ref: '#/definitions/SimpleResponse'
  /healthz:
    get:
      operationId: HealthCheck
      tags:
        - health-checks
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SimpleResponse'
      security: []
definitions:
  Resource:
    type: object
    properties:
      resourceId:
        type: string
        description: resourceId
  SimpleResponse:
    type: object
    properties:
      id:
        type: string
      message:
        type: string
 